### ISSUE TITLE
Is LoRA fine-tuning supported? 

### ISSUE THREAD

**Issue by WangRongsheng** [ollanoinc/hyvideo#2]
This is a very cool repo, and I want to know if it's possible to use this repo to perform LoRA fine-tuning training on HunyuanVideo?

**Comment by ghunkins** [comment]
Hi @WangRongsheng , it will be available in `diffusers` shortly, see comment here: https://github.com/huggingface/diffusers/pull/10136#issuecomment-2543126647.

**Comment by WangRongsheng** [comment]
thank you
